### ISSUE TITLE
Issues and clarifications 

### ISSUE THREAD

**Issue by hardrock1234** [Incapsula/logs-downloader#1]
Hi , 
This is a great script and thank you for sharing your hard work!

Couple of questions:

We have couple of website behind incapsula application firewall, we are a charity company and like to get the security logs / system logs from our application

Can you clarify the followings please:
1: Inside that folder, save the private key with the name Private.key.  where do you get the Private key i thought the data transfer is based on the API ID & Key ?

2: This is of course not a valid URL BASEURL=https://logging.incapsula.com/123456_456789.  ?

Much appreciate your reply! 

Regards, 
LS

**Comment by DoronLehmann** [comment]
Hi,

If you need additional information regarding enabling logs from Incapsula for your sites,
please contact our customer support.

Regarding your questions:

1. You need to generate a key pair and upload your public key to Incapsula. You will than have your own private key. For example:

    `openssl genrsa -out Private.pem 2048`
    `openssl rsa -in Private.pem -outform PEM -pubout -out Public.pem`
    `openssl pkcs8 -topk8 -in Private.pem -out Private.key –nocrypt`

1. You can get the relevant URL for your account from the logs settings page

Thanks,
Doron

**Comment by hardrock1234** [comment]
Thanks very much for your quick reply, just one more question:

Are you saying enabling logs is a seperate functionality ?  i see from our settings is not enabled!

Regards,

sza

**Comment by DoronLehmann** [comment]
Hi,

The logs feature is not enabled by default, if you wish to enable this functionality please contact Incapsula's support, they will be happy to provide you with all the relevant information.

Regards,
Doron

**Comment by hardrock1234** [comment]
Brilliant, Thanks very much for your help. 

- enable logging feature
- create and upload the keys  ? do we upload the key ourself or we provide incapsula to deploy the key ?
-  once we enabled the logging feature - i suspect we get individual URLs to get the logs from ?

Regards,

**Comment by DoronLehmann** [comment]
Hi,

1. You will need to upload your key yourself to Incapsula
2. As I mentioned, You will get the relevant URL for your account from the logs settings page

Regards,
Doron
