### ISSUE TITLE
Running on Windows

### ISSUE THREAD

**Issue by therealjoshhogle** [Incapsula/logs-downloader#15]
Documentation should be updated that in order to run on Windows with Python 2.7, you will need to also install "pycrypto" via PIP.  In addition, M2Crypto can be downloaded from here as it fails to build on Windows due to OpenSSL issues:
https://github.com/dsoprea/M2CryptoWindows

**Comment by BadRacoon** [comment]
@therealjoshhogle  - Have your successfully implemented the script on Windows?
I am dealing with a lot of issues (Connections, downloading index file, Decrypt the log files, preserve last index file downloaded, etc...)

**Comment by therealjoshhogle** [comment]
@BadRacoon I would open up a case with Incapsula support by emailing support@incapsula.com.  They should be able to point you in the right direction and help you.
