### ISSUE TITLE
Imperva API gives error  \"operation\" is missing","error-code":"IMP-10015"

### ISSUE THREAD

**Issue by akkice** [Incapsula/logs-downloader#28]
{"errors":[{"description":"Can not create \"applyTo\" since the body parameter \"operation\" is missing","error-code":"IMP-10015"}]}

While adding the IP address to any IP groups or putting any parameters in the custom policy as well. It can not create ApplyTO since the Operation is missing but there is no operation parameter in applyTO section.

**Comment by OmerLitov** [comment]
Hi, this repository is deprecated.
please download the script from https://github.com/imperva/incapsula-logs-downloader
