### ISSUE TITLE
Error -3 while decompressing

### ISSUE THREAD

**Issue by Zyanyalira** [Incapsula/logs-downloader#33]
Im downloading the logs and putting them into fail dir because I'm receiving his error, but I'm not encrypting my logs. 

INFO Saving file 3733_208462.log locally to the 'fail' folder Error -3 while decompressing: incorrect header check Traceback (most recent call last):
  File "LogsDownloader.py", line 222, in handle_file
    decrypted_file = self.decrypt_file(result[1], logfile)
  File "LogsDownloader.py", line 280, in decrypt_file
    uncompressed_and_decrypted_file_content = zlib.decompressobj().decompress(file_log_content)
error: Error -3 while decompressing: incorrect header check

**Comment by benyvo** [comment]
Hello, this error indicates that logs downloaded while they not compressed.
The py script try to decompress and fails. You need to mark compress in UI
That will fix the problem.
Beny

**Comment by Zyanyalira** [comment]
Hello @benyvo 
I have mark the compress in UI, but that didn't fixed it. Do you have any other idea?

**Comment by benyvo** [comment]
Hello, it takes time, it could not immediately changed. Since we have
backlog of about a hour.Try now.
Beny
