### ISSUE TITLE
SSLError - Exception 

### ISSUE THREAD

**Issue by AntonioKL** [Incapsula/logs-downloader#4]
Add an exception handler for connection timeout. 

![untitled](https://cloud.githubusercontent.com/assets/12611021/13140179/2db3d1a6-d639-11e5-97b0-43f9170ece92.png)

**Comment by DoronLehmann** [comment]
Hi,

The exception is handled as expected - an informative log is printed describing the issue, in addition to the trace.

Thanks,
Doron

**Comment by AntonioKL** [comment]
Well, the problem is not the log. The problem is that the script stops after this error and has to be restarted.
